export interface UserInfo {
    userId: number,
    emailAddress: string,
    password: string,
    firstName: string,
    lastName: string,
    idNumber: string,
    phoneNumber: string,
    accountNumber: string,
    streetAddress: string,
    city: string,
    country: string,
    state: string,
    zipCode: string,
} 