export interface VehicleInfo {
    vehicleId: number,
    manufacturerId: number,
    manufacturerName: string,
    modelName: string,
    year: number,
    price: number, 
    fuelType: string,
    transmission: string,
    displacement: number,
    power: number,
    torque: number,
    weight: number,
    bodyType: string,
    additionalInfo: string,
}